Initializing different types of arrays

In [3]:
import numpy as np

In [9]:
a = np.zeros((2, 3))

In [11]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
a.dtype

dtype('float64')

In [13]:
a.size

6

In [14]:
b = np.ones((2,2))

In [15]:
b

array([[1., 1.],
       [1., 1.]])

In [16]:
c = np.full((2,2), 99)

In [17]:
c

array([[99, 99],
       [99, 99]])

In [19]:
c.dtype

dtype('int64')

In [25]:
# randome numbers
d = np.random.rand(2,3)
d

array([[0.95521111, 0.41462189, 0.8302223 ],
       [0.93801963, 0.52471363, 0.59495221]])

In [26]:
d.shape
e = np.random.random_sample(d.shape)
e
#it takes the shape of d

array([[0.50058338, 0.24506026, 0.09239529],
       [0.92327474, 0.24149591, 0.56565568]])

In [35]:
#random integers
np.random.randint(11,size=(3,3))
#random integers between 0 - 10

array([[0, 6, 8],
       [3, 7, 2],
       [9, 5, 4]])

In [47]:
np.random.randint(-10, 10, size=(3,3))
#random integers between (-11, 11), or [-10, 10]

array([[  7,   9,   9],
       [  5, -10, -10],
       [ -9,   9,   2]])

In [49]:
np.identity(4, dtype=int)
#identity matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [51]:
f = np.array([1,2,4])
g = np.repeat(f, 3)
g
#repeat array f 3 times

array([1, 1, 1, 2, 2, 2, 4, 4, 4])

In [68]:
#for 2d arrays
h = np.array([[1,2,3]])
i = np.repeat(h, 4, axis=0)
i
#axis = 0 => repeat by adding columns
#axix = 1 => repeat by adding the same element to the existing row

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [84]:
#lets build a matrix with a pattern
output = np.ones((5,5), dtype = int)
print(output)
z = np.zeros((3,3), dtype = int)
z[1,1] = 9
print(z)
output[1:-1, 1:-1] = z
print(" ")
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
 
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [88]:
a = np.array([1,2,3])
b = a.copy()
b[1] = 5
b
#copy a, chaning the values in b won't change the values in a

array([1, 5, 3])