In [2]:
import numpy as np

In [13]:
a = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]], dtype='int16')
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [14]:
a.size

20

In [15]:
a.shape

(2, 10)

In [16]:
a.nbytes

40

In [17]:
a.dtype

dtype('int16')

In [18]:
a.itemsize

2

In [20]:
a.itemsize

2

In [22]:
a.size

20

In [23]:
a.shape

(2, 10)

In [26]:
a.nbytes

40

In [29]:
a.dtype

dtype('int16')

In [35]:
a[:, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]], dtype=int16)

In [38]:
a[1, :]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20], dtype=int16)

In [39]:
a[:, 7]

array([ 8, 18], dtype=int16)

In [42]:
a[0:2:1]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]], dtype=int16)

In [44]:
a[:, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]], dtype=int16)

In [47]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7  8  9 10]
 [11 12  5 14 15 16 17 18 19 20]]


In [46]:
print(a)

[[ 1  2  5  4  5  6  7  8  9 10]
 [11 12  5 14 15 16 17 18 19 20]]
