In [1]:
import numpy as np

In [11]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [18]:
a.shape

(3,)

In [19]:
a.size

3

In [20]:
a.dtype

dtype('int64')

In [28]:
b = np.random.rand((3))
b
b.ndim

1

In [36]:
c = np.full((3,3), 0)
c

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [40]:
d = np.random.rand(2,2)
d

array([[0.12085648, 0.62446956],
       [0.23838514, 0.88149584]])

In [41]:
e = np.random.randint(2,6)
e

4

In [44]:
f = np.random.randint(1,10,6)
f

array([7, 6, 1, 5, 4, 7], dtype=int32)

In [47]:
g = np.random.randint(1,10,(4,4))
g

array([[9, 4, 4, 9],
       [4, 4, 3, 3],
       [8, 3, 8, 1],
       [2, 1, 8, 6]], dtype=int32)

In [48]:
g[:,:]
#print all rows and cloums

array([[9, 4, 4, 9],
       [4, 4, 3, 3],
       [8, 3, 8, 1],
       [2, 1, 8, 6]], dtype=int32)

In [53]:
g[1:,1:]
# print all rows and colums after row 1 and after column 1

array([[4, 3, 3],
       [3, 8, 1],
       [1, 8, 6]], dtype=int32)

In [55]:
g[1:,:2]
# print all rows after 1st row and all colums before the second one

array([[4, 4],
       [8, 3],
       [2, 1]], dtype=int32)

In [57]:
g[1:3, 1:3]
# print 1st inclusive to 3rd exlusive row and colums

array([[4, 3],
       [3, 8]], dtype=int32)

In [59]:
g[1:3,1:3].flatten()

array([4, 3, 3, 8], dtype=int32)